# Generated by Django 6.0.2 on 2026-03-16 18:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('route_date', models.DateField()),
                ('route_data', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('route_color', models.CharField(max_length=7)),
                ('route_layer', models.IntegerField()),
                ('route_visible', models.BooleanField(default=True)),
                ('route_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorastory_app.route')),
            ],
        ),
    ]
